#!/bin/bash

set -e

script_dir="$(dirname "$0")"
arch="$(uname -p)"

custom=false
fixed=false
case "$1" in
    --image-build)
        shift
        custom=true
        ;;
    --pxe)
        shift
        fixed=true
        ;;
    --all)
        shift
        ;&
    *)
        custom=true
        fixed=true
        ;;
esac

DEST_DIR="$1"
# Extract coreos ISOs in same path as DEST_DIR (which has a writable mount),
# so that we don't get an exception when ReadOnlyRootFilesystem flag is set
# to true for this container in the CBO
ISO_DIR_WRITABLE="${1}/coreos"

if [ ! -d "${ISO_DIR_WRITABLE}" ]; then
    mkdir -p "${ISO_DIR_WRITABLE}"
fi

# ISOs need to be available before running copy-pxe and copy-iso.
if [[ "${arch}" == "x86_64" ]]; then
    MACHINE_OS_IMAGES_IMAGE="${MACHINE_OS_IMAGES_IMAGE:-}"

    if [ -n "${MACHINE_OS_IMAGES_IMAGE}" ]; then
        base64 -d /run/secrets/pull-secret > /run/secrets/auth.json
        oc image extract \
            --certificate-authority=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem \
            --registry-config=/run/secrets/auth.json \
            --path=/coreos/coreos-aarch64.iso:"${ISO_DIR_WRITABLE}/" \
            --filter-by-os=linux/arm64 \
            --confirm \
            "${MACHINE_OS_IMAGES_IMAGE}" || echo "failed to extract aarch64 ISO"
        jq -r ".architectures.aarch64.artifacts.metal.formats.iso.disk.sha256" /coreos/coreos-stream.json > "${ISO_DIR_WRITABLE}/coreos-aarch64.iso.sha256"
    else
        echo "MACHINE_OS_IMAGES_IMAGE is unset.  Skipping aarch64 iso extraction."
    fi
fi

if [ $fixed = true ]; then
    "${script_dir}/copy-pxe" "${DEST_DIR}"
    ln -f -s "coreos-${arch}-vmlinuz" "${DEST_DIR}/ironic-python-agent.kernel"
    ln -f -s "coreos-${arch}-vmlinuz" "${DEST_DIR}/ironic-python-agent_${arch}.kernel"
    ln -f -s "coreos-${arch}-rootfs.img" "${DEST_DIR}/ironic-python-agent.rootfs"
    ln -f -s "coreos-${arch}-rootfs.img" "${DEST_DIR}/ironic-python-agent_${arch}.rootfs"

    if [[ "${arch}" == "x86_64" ]]; then
        ln -f -s "coreos-aarch64-vmlinuz" "${DEST_DIR}/ironic-python-agent_aarch64.kernel"
        ln -f -s "coreos-aarch64-rootfs.img" "${DEST_DIR}/ironic-python-agent_aarch64.rootfs"
    fi

else
    "${script_dir}/copy-pxe" --initrd-only "${DEST_DIR}"
    rm -f "${DEST_DIR}"/coreos-*-vmlinuz "${DEST_DIR}"/coreos-*-rootfs.img
fi

if [ $custom = true ]; then
    ln -f -s "coreos-${arch}-initrd.img" "${DEST_DIR}/ironic-python-agent.initramfs"
    ln -f -s "coreos-${arch}-initrd.img" "${DEST_DIR}/ironic-python-agent_${arch}.initramfs"

    "${script_dir}/copy-iso" "${DEST_DIR}"
    ln -f -s "coreos-${arch}.iso" "${DEST_DIR}/ironic-python-agent.iso"
    ln -f -s "coreos-${arch}.iso" "${DEST_DIR}/ironic-python-agent_${arch}.iso"


    if [[ "${arch}" == "x86_64" ]]; then
        ln -f -s "coreos-aarch64-initrd.img" "${DEST_DIR}/ironic-python-agent_aarch64.initramfs"
        ln -f -s "coreos-aarch64.iso" "${DEST_DIR}/ironic-python-agent_aarch64.iso"
    fi
fi
